//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBLnh2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSHoKhau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSHoKhau()
        {
            this.Thongtinnhankhaus = new HashSet<Thongtinnhankhau>();
        }
    
        public int SoSHK { get; set; }
        public string Chuho { get; set; }
        public string Ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongtinnhankhau> Thongtinnhankhaus { get; set; }
    }
}
