//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBLnh2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamtru
    {
        public string Noiden { get; set; }
        public string Noidi { get; set; }
        public string Ghichu { get; set; }
        public Nullable<System.DateTime> Thoigiandichuyen { get; set; }
        public int CMND { get; set; }
    }
}
